name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - client/**

jobs:
  deploy:
    name: Deploy to Github Pages
    permissions:
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          cd client
          yarn
          yarn exec vite build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: client/dist
